apiVersion: apps/v1
kind: Deployment
metadata:
  name: bodybuilderhub-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bodybuilderhub
  template:
    metadata:
      labels:
        app: bodybuilderhub
    spec:
      containers:
      - name: bodybuilderhub-container
        image: bodybuilder-app:latest
        imagePullPolicy: Never       # ← tell k8s to use local image only
        ports:
        - containerPort: 3000

